spring:
  application:
    name: requesttracker
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .html
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://avnadmin:AVNS_On7aJsdh-AHHoFWJy0P@mysql-384c46e4-requesttrack.a.aivencloud.com:25571/requesttrack?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_On7aJsdh-AHHoFWJy0P
    driver-class-name: com.mysql.cj.jdbc.Driver


    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: aravinth.a@telliant.net
    password: zFUY6CakfJgpD4R3
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

springdoc:
  api-docs:
    path: /api-docs

app:
  jwtCookieName: Spring
  jwtSecret: =================================Spring===========================
  jwtExpirationMs: 600000

# Additional properties...
